apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Salay1942/argocd.git'
    targetRevision: HEAD
    path: 'manifests/myweb' # Adjust this to your actual path
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myweb-namespace # Specify the target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
